In [1]:
a = (2, 3)

In [3]:
import torch

In [57]:
a = torch.Tensor([[3, 2],[2,2]])

In [71]:
import torchvision.transforms as transforms
import os
from PIL import Image
img = transforms.ToTensor()(Image.open(os.getcwd() + '/yolo_helmet_train/anno/images/000002.jpg').convert('RGB'))

In [88]:
img.shape

torch.Size([3, 332, 500])

In [87]:
img = img.squeeze(0)

In [90]:
img.expand((3, img.numpy().shape[1:]))

TypeError: expand(): argument 'size' must be tuple of ints, but found element of type tuple at pos 2

In [82]:
a.shape[1:]

AttributeError: 'torch.Size' object has no attribute 'numpy'

In [2]:
import numpy as np
boxes = np.loadtxt(os.getcwd() + '/yolo_helmet_train/anno/labels/000002.txt').reshape(-1, 5)

array([[1.        , 0.113     , 0.1746988 , 0.078     , 0.15662651],
       [1.        , 0.222     , 0.18975904, 0.056     , 0.11445783],
       [1.        , 0.373     , 0.39307229, 0.086     , 0.16566265],
       [1.        , 0.391     , 0.27710843, 0.07      , 0.12650602],
       [1.        , 0.472     , 0.19879518, 0.06      , 0.13253012],
       [1.        , 0.532     , 0.26054217, 0.068     , 0.15361446],
       [1.        , 0.711     , 0.25903614, 0.082     , 0.15662651],
       [1.        , 0.729     , 0.40662651, 0.082     , 0.1686747 ],
       [1.        , 0.774     , 0.25451807, 0.06      , 0.15361446],
       [1.        , 0.863     , 0.32078313, 0.09      , 0.17771084],
       [0.        , 0.055     , 0.2996988 , 0.074     , 0.14759036]])

In [13]:
import torch
arr = torch.from_numpy(boxes).unsqueeze(0)

In [40]:
a = torch.ones((3, 2))
b = torch.ones(3, 2) * 2


In [46]:
c = torch.cat((a, b), 1)

In [47]:
c

tensor([[1., 1., 2., 2.],
        [1., 1., 2., 2.],
        [1., 1., 2., 2.]])

In [64]:
a = torch.rand([1, 2, 3])

In [72]:
a[..., [1]]

tensor([[[0.9138],
         [0.7206]]])

In [77]:
torch.arange(13).repeat(13, 1).view([1, 1, 13, 13]).type(torch.FloatTensor)

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
          [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]

In [82]:
anchors = [(15, 16), (123, 123), (290, 308)]
scaled_anchors = torch.FloatTensor([(a_w/ 32, a_h/32) for a_w, a_h in anchors])
scaled_anchors

tensor([[0.4688, 0.5000],
        [3.8438, 3.8438],
        [9.0625, 9.6250]])

In [85]:
anchor_w = scaled_anchors[:, 0:1].view((1, 3, 1, 1))
scaled_anchors.t()

tensor([[0.4688, 3.8438, 9.0625],
        [0.5000, 3.8438, 9.6250]])